export const FETCH_SYSTEM_PROPERTIES_START = 'FETCH_SYSTEM_PROPERTIES_START';
export const SET_SYSTEM_PROPERTIES = 'SET_SYSTEM_PROPERTIES';
export const FETCH_SYSTEM_PROPERTIES_FAILED = 'FETCH_SYSTEM_PROPERTIES_FAILED';
export const CREATE_SYSTEM_PROPERTY = 'CREATE_SYSTEM_PROPERTY';
export const SYSTEM_PROPERTY_SUCCESS = 'SYSTEM_PROPERTY_SUCCESS';
export const SYSTEM_PROPERTY_FAILED = 'SYSTEM_PROPERTY_FAILED';
